"""empty message

Revision ID: 48bc484dfd00
Revises: 4d393c1dc851
Create Date: 2022-05-30 19:11:38.054237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48bc484dfd00'
down_revision = '4d393c1dc851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image', sa.String(length=255), nullable=True))
    op.drop_column('products', 'img_banner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('img_banner', sa.VARCHAR(length=2500), autoincrement=False, nullable=True))
    op.drop_column('categories', 'image')
    # ### end Alembic commands ###
