"""empty message

Revision ID: 4d393c1dc851
Revises: b02c4228a436
Create Date: 2022-05-30 15:11:18.944537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d393c1dc851'
down_revision = 'b02c4228a436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.String(length=250), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=250), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=250), nullable=True))
    op.drop_column('users', 'default_shipping_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_shipping_address', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('users', 'address')
    op.drop_column('users', 'city')
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
