"""empty message

Revision ID: 990269566384
Revises: c8520f60c1ff
Create Date: 2022-05-22 20:43:29.379835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990269566384'
down_revision = 'c8520f60c1ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'description_2',
               existing_type=sa.VARCHAR(length=5000),
               nullable=True)
    op.alter_column('products', 'description_3',
               existing_type=sa.VARCHAR(length=5000),
               nullable=True)
    op.alter_column('products', 'description_4',
               existing_type=sa.VARCHAR(length=5000),
               nullable=True)
    op.alter_column('products', 'tittle_description_2',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('products', 'tittle_description_3',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('products', 'tittle_description_4',
               existing_type=sa.VARCHAR(length=5000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'tittle_description_4',
               existing_type=sa.VARCHAR(length=5000),
               nullable=False)
    op.alter_column('products', 'tittle_description_3',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('products', 'tittle_description_2',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('products', 'description_4',
               existing_type=sa.VARCHAR(length=5000),
               nullable=False)
    op.alter_column('products', 'description_3',
               existing_type=sa.VARCHAR(length=5000),
               nullable=False)
    op.alter_column('products', 'description_2',
               existing_type=sa.VARCHAR(length=5000),
               nullable=False)
    # ### end Alembic commands ###
